version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  deploy:
    docker:
      # This image has the latest cf-cli as well as zero downtime plugins, if needed.
      - image: circleci/node:14.18.2-browsers
    resource_class: medium+
    steps:
      - checkout
      - run:
          name: install nasm
          command: sudo apt install nasm
      - restore_cache:
          key: v3-node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: rm -rf node_modules && rm ./package-lock.json
      - run:
          name: "list generated downloads"
          command: |
            ls -lart static/downloads
           # rm static/downloads/downloads.json
      - run:
          name: "list generated downloads"
          command: |
            ls -lart static/downloads
      - run:
          name: npm install
          command: npm install
      - run:
          name: Build Gatsby
          command: npm run build
      # - run:
      #     name: deploy preview to cloud.gov
      #     command: |
      #       pwd && ls -l
      #       curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
      #       sudo dpkg -i cf-cli_amd64.deb
      #       cp Staticfile ./public
      #       # Set $CF_USERNAME and $CF_PASSWORD in CircleCI settings.
      #       # $CF_ORG, $CF_SPACE, and $APP_NAME can also be set in CircleCI settings or hardcoded here.
      #       cf api https://api.fr.cloud.gov
      #       cf auth "$PROD_CF_USERNAME" "$PROD_CF_PASSWORD"
      #       cf target -o "$PROD_CF_ORG" -s "$PROD_CF_SPACE"
      #       bash ./swap.sh
      #       cf push nrrd -f ./manifest.yml
workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
